import logging

import model.tools.data_service as data_service
import model.tools.config_service as config_service
import model.tools.monitor_service as monitor_service
import model.crawler.fetching_service as fetching_service
import model.crawler.discovery_service as discovery_service
import asyncio
import time
import model.analyzer.category_service as category_service
import model.analyzer.extraction_service as extraction_service
import model.analyzer.entity_service as entity_service
from model.tools import page_store, url_service
from model.objects.website import Website

logger = logging.getLogger(__name__)

discovery_queries: list[str] = []  # search queries generated by init(), consumed by run_discovery()


def init():
    """
    Prepare a crawl run: initialize the database schema, seed the fetch
    queue from starting_urls/prior crawls (model.crawler.fetching_service.init()),
    and - if search-based discovery is enabled in the config - generate and
    store the search queries later consumed by run_discovery().
    """
    config = config_service.get_config()
    data_service.init_db()
    page_store.configure(config.page_store_path)
    fetching_service.init(
        starting_url_path = config.get_starting_url_path(),
        redo_failed_fetches=config.redo_failed_fetches,
        redo_all_fetches=config.redo_all_fetches
    )
    global discovery_queries
    discovery_queries = discovery_service.read_query_templates(config.get_search_query_path()) if config.discover_urls else []
    logger.info(
        "Initialized: %d URL(s) queued, %d discovery quer%s available",
        len(fetching_service.url_queue), len(discovery_queries),
        "y" if len(discovery_queries) == 1 else "ies",
    )
    # Finish work left over from an earlier run before fetching anything new,
    # so an interruption never leaves a permanently growing tail of
    # fetched-but-unprocessed pages.
    resume_pending()

def run_discovery():
    """
    Consume up to config.discovery_batch_size queries off the front of
    discovery_queries (generated by init()), run them against the
    configured search provider, and queue any newly discovered URLs for
    crawling. No-op if search-based discovery is disabled in the config, or
    if there are no queries left to consume.

    Queries are consumed (removed from discovery_queries) as they're used,
    so repeated calls work through the whole query list batch by batch
    instead of re-running the same queries - see run()'s docstring for why
    that matters.

    :return: number of URLs newly added to the fetch queue.
    """
    config = config_service.get_config()
    if not config.discover_urls or not discovery_queries:
        return 0
    batch = discovery_queries[:config.discovery_batch_size]
    del discovery_queries[:config.discovery_batch_size]
    discovered = discovery_service.discover_urls(
        config.get_search_provider(),
        batch,
        results_per_query=config.results_per_query,
        politeness=config.query_politeness,
    )
    added = discovery_service.queue_discovered_urls(discovered)
    monitor_service.discovery(
        queries_used=len(batch),
        discovered_unique=len(discovered),
        newly_queued=added,
        queries_remaining=len(discovery_queries),
    )
    logger.info("Discovery batch: %d new URL(s) queued (%d queries remaining)", added, len(discovery_queries))
    return added

def run():
    """
    Run the full crawl workflow end-to-end.

    init() seeds the fetch queue from starting_urls/prior crawls and
    generates (but does not yet run) the search-discovery queries. The
    fetch queue is then drained via process_batch() - which keeps it
    growing on its own as extraction discovers linked pages - and only once
    it runs completely dry does the workflow reach for search-engine
    discovery, via run_discovery(). That deliberately holds discovery back
    until crawling from the known/linked URLs has nothing left to do,
    rather than queuing every discovered URL upfront: it keeps discovery
    query usage proportional to how much the "cheap" crawl sources actually
    ran out, instead of firing every query in one burst regardless of need.

    Once run_discovery() has run, the loop goes back to draining the queue;
    if a discovery batch turned up nothing new, the next batch is tried
    (subject to the stopping conditions below) until either the queue has
    work again or there are no queries left.

    Stopping conditions (checked after every batch or discovery call, first
    one to trigger wins):
      - the fetch queue is empty AND there are no discovery queries left to try
      - config.max_discovery_batches discovery batches have been run (0 = no limit)
      - config.max_rounds fetch/process batches have been processed (0 = no limit)
      - config.max_runtime_seconds have elapsed since the run started (0 = no limit)
    """
    config = config_service.get_config()
    logger.info("Starting crawl run")
    monitor_service.start_session()
    init()

    start_time = time.monotonic()
    rounds = 0
    discovery_batches_used = 0
    stop_reason = "queue and discovery queries exhausted"

    def _time_or_round_limit_reached():
        nonlocal stop_reason
        if config.max_rounds and rounds >= config.max_rounds:
            stop_reason = f"reached max_rounds ({config.max_rounds})"
            return True
        if config.max_runtime_seconds and (time.monotonic() - start_time) >= config.max_runtime_seconds:
            stop_reason = f"reached max_runtime_seconds ({config.max_runtime_seconds})"
            return True
        return False

    while True:
        if not fetching_service.url_queue:
            discovery_budget_left = not config.max_discovery_batches or discovery_batches_used < config.max_discovery_batches
            if not discovery_queries or not discovery_budget_left:
                if discovery_queries and not discovery_budget_left:
                    stop_reason = f"reached max_discovery_batches ({config.max_discovery_batches})"
                break  # nothing left to crawl, and no (more) discovery queries allowed
            run_discovery()
            discovery_batches_used += 1
            if _time_or_round_limit_reached():
                break
            continue  # queue may still be empty - loop back and try the next discovery batch

        process_batch()
        rounds += 1
        if _time_or_round_limit_reached():
            break

    elapsed = time.monotonic() - start_time
    logger.info(
        "Crawl run finished: %d batch(es), %d discovery batch(es), %.1fs elapsed (%s)",
        rounds, discovery_batches_used, elapsed, stop_reason,
    )
    monitor_service.session_end(rounds, discovery_batches_used, elapsed, stop_reason)

def process_batch(urls:list[str]|None=None):
    """
    Run one fetch-categorize-extract pass: fetch every URL currently queued
    (plus any given explicitly), categorize each successfully fetched page,
    extract structured data per its category, save everything to the
    database, and queue any linked pages extraction found for a future batch.

    Brackets the pass with monitor_service.round_start()/round_end() - see
    model.tools.monitor_service and experiments/analyze_session.py for how
    those timestamps are later used to bin this round's crawls (fetched/
    failed/categorized counts, all already in the database) out of the
    crawls table. Also times each page's categorize_website()/
    extract_information() calls individually and logs them via
    monitor_service.page() - unlike the round-level counts, this timing data
    only exists in the monitoring log, since the database doesn't record it.

    :param urls: extra URLs to queue before this batch runs, in addition to
                  whatever is already in fetching_service.url_queue.
    """

    ### Fetching
    if urls is not None:
        for url in urls:
            fetching_service.queue_url(url)
    batch = fetching_service.url_queue
    round_number = monitor_service.round_start(len(batch))
    logger.info("Processing batch of %d URL(s) (round %d)", len(batch), round_number)
    asyncio.run(fetching_service.parse_queue())
    fetched = []
    for url in batch:
        html = asyncio.run(fetching_service.get_content(url))
        crawl_time = fetching_service.get_crawl_time(url)
        fetch_success = bool(html)
        # Persist the body *before* recording the crawl, so a row never points
        # at content that isn't on disk. The row's state stays non-terminal
        # until the page is actually processed, so an interruption here leaves
        # resumable work rather than a page marked done that never was.
        # Already persisted at fetch time (fetching_service.get_content); reuse
        # that path rather than storing the same bytes twice.
        digest, content_path = fetching_service.fetched_content.get(url, (None, None))
        if fetch_success and content_path is None:
            digest, content_path = page_store.store(html)
        crawl_id = data_service.save_crawl_instance(
            url, crawl_time, fetch_success,
            content_path=content_path, content_sha256=digest,
            site=url_service.registrable_domain(url),
        )
        if fetch_success:
            fetched.append((crawl_id, Website(url=url, crawl_time=crawl_time, html=html)))
    if batch:
        logger.info("Fetched %d/%d URL(s) successfully", len(fetched), len(batch))

    ### Categorization + extraction, page by page
    for crawl_id, website in fetched:
        process_page(crawl_id, website.url, website.html)

    monitor_service.round_end()


def process_page(crawl_id:int, url:str, html:str, category=None):
    """
    Take one fetched page from its current state to EXTRACTED.

    Each stage commits before the next begins, so an interruption leaves the
    page recorded at exactly the point it reached and a later run continues
    from there rather than refetching or reprocessing it.

    :param category: an already-determined Category (when resuming a page that
                      was categorized but not extracted); None to categorize now.
    """
    categorize_seconds = 0.0
    if category is None:
        categorize_start = time.monotonic()
        category = category_service.categorize_website(html, url)
        categorize_seconds = time.monotonic() - categorize_start
        if category is None:
            # category_service already logged why - one bad page (e.g. too
            # long for the model's context window) must not crash the run
            logger.warning("Skipping %s - categorization failed", url)
            monitor_service.page(url, None, categorize_seconds, 0.0)
            data_service.set_crawl_state(crawl_id, data_service.STATE_FAILED,
                                         last_error="categorization failed")
            return
        data_service.save_site_category(crawl_id, category.name)
        data_service.set_crawl_state(crawl_id, data_service.STATE_CATEGORIZED)
        logger.info("Categorized %s as %s", url, category.name)

    extract_start = time.monotonic()
    extracted = extraction_service.extract_information(html, category, url)
    monitor_service.page(url, category.name, categorize_seconds, time.monotonic() - extract_start)

    # Clear anything a previous attempt at this page wrote, so reprocessing
    # (after a crash, or a deliberate replay) can never double-insert.
    data_service.delete_entries_for_crawl(crawl_id)

    if extracted:
        extracted_data, links = extracted
        if extracted_data is None:
            # Either a LINKS category (nothing on the page itself is worth
            # extracting) or a CONTENT category whose record failed the
            # admissibility gate. Both keep the page's outbound links.
            logger.debug("No content to extract from %s (category=%s), following %d link(s)", url, category.name, len(links))
        elif category.is_list_category:
            for entry in extracted_data:
                data_service.save_extraction(crawl_id, entry)
            logger.info("Extracted %d entries from %s", len(extracted_data), url)
        else:
            data_service.save_extraction(crawl_id, extracted_data)
            logger.info("Extracted %d field(s) from %s", len(extracted_data), url)
        for link in links:
            fetching_service.queue_url(link)
    else:
        logger.debug("No data extracted from %s (category=%s)", url, category.name)

    data_service.set_crawl_state(crawl_id, data_service.STATE_EXTRACTED)


def resume_pending():
    """
    Finish pages left unprocessed by an earlier run.

    Pages fetched but never categorized (or categorized but never extracted)
    are still in a non-terminal state, and their content is on disk, so they
    are resumed from exactly where they stopped - with no refetching. Content
    that has gone missing from the store is returned to the fetch queue rather
    than silently dropped.

    :return: number of pages processed.
    """
    pending = data_service.get_pending_crawls()
    if not pending:
        return 0

    logger.info("Resuming %d unprocessed page(s) from a previous run", len(pending))
    processed = 0
    for row in pending:
        html = page_store.load(row["content_path"])
        if not html:
            logger.warning("Stored content missing for %s - requeueing", row["source_url"])
            data_service.set_crawl_state(row["crawl_id"], data_service.STATE_FETCH_FAILED,
                                         last_error="stored content missing")
            fetching_service.queue_url(row["source_url"])
            continue
        category = None
        if row["category"]:
            try:
                category = config_service.get_config().get_category(row["category"])
            except Exception:
                category = None  # category set no longer matches config - redo it
        process_page(row["crawl_id"], row["source_url"], html, category)
        processed += 1
    logger.info("Resumed %d page(s)", processed)
    return processed

def resolve_entities():
    """
    Deduplicate the observation records in `entries` into `entities`.

    Runs blocking -> scoring -> clustering -> fusion over everything extracted
    so far, using the field roles declared in the config, and replaces the
    entity layer with the result. `entries` itself is never modified, so this
    can be re-run after tuning weights without re-crawling.

    :return: (record_count, entity_count)
    """
    config = config_service.get_config()
    data_service.init_db()
    data_service.init_entity_tables()

    records = data_service.get_entries_with_source()
    if not records:
        logger.info("No extracted records to resolve")
        return 0, 0

    for record in records:
        # A record found on the entity's own site outranks one copied into a
        # third-party directory, which is often abbreviated or stale.
        own = url_service.registrable_domain(record.get("station_url") or "")
        source = url_service.registrable_domain(record.get("_source_url") or "")
        record["_trust"] = 1.0 if own and own == source else 0.5

    resolver = entity_service.Resolver(field_semantics=config.field_semantics)
    clusters = resolver.cluster(records)
    resolved = [(resolver.fuse(cluster), [r["entry_id"] for r in cluster])
                for cluster in clusters]
    data_service.replace_entities(resolved)

    logger.info("Resolved %d record(s) into %d entit%s (%.1f%% duplicates removed)",
                len(records), len(clusters), "y" if len(clusters) == 1 else "ies",
                100 * (1 - len(clusters) / len(records)))
    return len(records), len(clusters)


def reprocess(stage="extract", where_site=None):
    """
    Re-run analysis over already-stored pages, without any network traffic.

    Because every fetched body is kept in the page store, categorization and
    extraction can be redone after changing a prompt, a model, a token budget
    or the schema - on exactly the same corpus, which is what makes such
    comparisons controlled rather than confounded by a re-crawl.

    :param stage: "extract" re-runs extraction only (keeping categories);
                   "categorize" re-runs classification as well.
    :param where_site: limit to one registrable domain.
    :return: number of pages queued for reprocessing.
    """
    data_service.init_db()
    page_store.configure(config_service.get_config().page_store_path)
    target = (data_service.STATE_CATEGORIZED if stage == "extract"
              else data_service.STATE_FETCHED)
    reset = data_service.reset_states_for_reprocess(target, site=where_site)
    logger.info("Reset %d page(s) to %s for reprocessing", reset, target)
    processed = resume_pending()
    logger.info("Reprocessed %d page(s) with no refetching", processed)
    return processed
