import logging

import model.tools.data_service as data_service
import model.tools.config_service as config_service
import model.tools.monitor_service as monitor_service
import model.crawler.fetching_service as fetching_service
import model.crawler.discovery_service as discovery_service
import asyncio
import time
import model.analyzer.category_service as category_service
import model.analyzer.extraction_service as extraction_service
from model.objects.website import Website

logger = logging.getLogger(__name__)

discovery_queries: list[str] = []  # search queries generated by init(), consumed by run_discovery()


def init():
    """
    Prepare a crawl run: initialize the database schema, seed the fetch
    queue from starting_urls/prior crawls (model.crawler.fetching_service.init()),
    and - if search-based discovery is enabled in the config - generate and
    store the search queries later consumed by run_discovery().
    """
    config = config_service.get_config()
    data_service.init_db()
    fetching_service.init(
        starting_url_path = config.get_starting_url_path(),
        redo_failed_fetches=config.redo_failed_fetches,
        redo_all_fetches=config.redo_all_fetches
    )
    global discovery_queries
    discovery_queries = discovery_service.read_query_templates(config.get_search_query_path()) if config.discover_urls else []
    logger.info(
        "Initialized: %d URL(s) queued, %d discovery quer%s available",
        len(fetching_service.url_queue), len(discovery_queries),
        "y" if len(discovery_queries) == 1 else "ies",
    )

def run_discovery():
    """
    Consume up to config.discovery_batch_size queries off the front of
    discovery_queries (generated by init()), run them against the
    configured search provider, and queue any newly discovered URLs for
    crawling. No-op if search-based discovery is disabled in the config, or
    if there are no queries left to consume.

    Queries are consumed (removed from discovery_queries) as they're used,
    so repeated calls work through the whole query list batch by batch
    instead of re-running the same queries - see run()'s docstring for why
    that matters.

    :return: number of URLs newly added to the fetch queue.
    """
    config = config_service.get_config()
    if not config.discover_urls or not discovery_queries:
        return 0
    batch = discovery_queries[:config.discovery_batch_size]
    del discovery_queries[:config.discovery_batch_size]
    discovered = discovery_service.discover_urls(
        config.get_search_provider(),
        batch,
        results_per_query=config.results_per_query,
        politeness=config.query_politeness,
    )
    added = discovery_service.queue_discovered_urls(discovered)
    monitor_service.discovery(
        queries_used=len(batch),
        discovered_unique=len(discovered),
        newly_queued=added,
        queries_remaining=len(discovery_queries),
    )
    logger.info("Discovery batch: %d new URL(s) queued (%d queries remaining)", added, len(discovery_queries))
    return added

def run():
    """
    Run the full crawl workflow end-to-end.

    init() seeds the fetch queue from starting_urls/prior crawls and
    generates (but does not yet run) the search-discovery queries. The
    fetch queue is then drained via process_batch() - which keeps it
    growing on its own as extraction discovers linked pages - and only once
    it runs completely dry does the workflow reach for search-engine
    discovery, via run_discovery(). That deliberately holds discovery back
    until crawling from the known/linked URLs has nothing left to do,
    rather than queuing every discovered URL upfront: it keeps discovery
    query usage proportional to how much the "cheap" crawl sources actually
    ran out, instead of firing every query in one burst regardless of need.

    Once run_discovery() has run, the loop goes back to draining the queue;
    if a discovery batch turned up nothing new, the next batch is tried
    (subject to the stopping conditions below) until either the queue has
    work again or there are no queries left.

    Stopping conditions (checked after every batch or discovery call, first
    one to trigger wins):
      - the fetch queue is empty AND there are no discovery queries left to try
      - config.max_discovery_batches discovery batches have been run (0 = no limit)
      - config.max_rounds fetch/process batches have been processed (0 = no limit)
      - config.max_runtime_seconds have elapsed since the run started (0 = no limit)
    """
    config = config_service.get_config()
    logger.info("Starting crawl run")
    monitor_service.start_session()
    init()

    start_time = time.monotonic()
    rounds = 0
    discovery_batches_used = 0
    stop_reason = "queue and discovery queries exhausted"

    def _time_or_round_limit_reached():
        nonlocal stop_reason
        if config.max_rounds and rounds >= config.max_rounds:
            stop_reason = f"reached max_rounds ({config.max_rounds})"
            return True
        if config.max_runtime_seconds and (time.monotonic() - start_time) >= config.max_runtime_seconds:
            stop_reason = f"reached max_runtime_seconds ({config.max_runtime_seconds})"
            return True
        return False

    while True:
        if not fetching_service.url_queue:
            discovery_budget_left = not config.max_discovery_batches or discovery_batches_used < config.max_discovery_batches
            if not discovery_queries or not discovery_budget_left:
                if discovery_queries and not discovery_budget_left:
                    stop_reason = f"reached max_discovery_batches ({config.max_discovery_batches})"
                break  # nothing left to crawl, and no (more) discovery queries allowed
            run_discovery()
            discovery_batches_used += 1
            if _time_or_round_limit_reached():
                break
            continue  # queue may still be empty - loop back and try the next discovery batch

        process_batch()
        rounds += 1
        if _time_or_round_limit_reached():
            break

    elapsed = time.monotonic() - start_time
    logger.info(
        "Crawl run finished: %d batch(es), %d discovery batch(es), %.1fs elapsed (%s)",
        rounds, discovery_batches_used, elapsed, stop_reason,
    )
    monitor_service.session_end(rounds, discovery_batches_used, elapsed, stop_reason)

def process_batch(urls:list[str]|None=None):
    """
    Run one fetch-categorize-extract pass: fetch every URL currently queued
    (plus any given explicitly), categorize each successfully fetched page,
    extract structured data per its category, save everything to the
    database, and queue any linked pages extraction found for a future batch.

    Brackets the pass with monitor_service.round_start()/round_end() - see
    model.tools.monitor_service and experiments/analyze_session.py for how
    those timestamps are later used to bin this round's crawls (fetched/
    failed/categorized counts, all already in the database) out of the
    crawls table.

    :param urls: extra URLs to queue before this batch runs, in addition to
                  whatever is already in fetching_service.url_queue.
    """

    ### Fetching
    if urls is not None:
        for url in urls:
            fetching_service.queue_url(url)
    batch = fetching_service.url_queue
    round_number = monitor_service.round_start(len(batch))
    logger.info("Processing batch of %d URL(s) (round %d)", len(batch), round_number)
    asyncio.run(fetching_service.parse_queue())
    websites = []
    crawl_ids = {}
    for url in batch:
        html = asyncio.run(fetching_service.get_content(url))
        crawl_time = fetching_service.get_crawl_time(url)
        fetch_success = bool(html)
        crawl_id = data_service.save_crawl_instance(url, crawl_time, fetch_success)
        crawl_ids[url] = crawl_id
        if fetch_success:
            websites.append(
                Website(
                    url = url,
                    crawl_time= crawl_time,
                    html = html,
                )
            )
    if batch:
        logger.info("Fetched %d/%d URL(s) successfully", len(websites), len(batch))

    ### Categorization
    categorized_websites = []
    for website in websites:
        url = website.url
        category = category_service.categorize_website(website.html)
        if category is None:
            # category_service already logged why - one bad page (e.g. too
            # long for the model's context window) must not crash the run
            logger.warning("Skipping %s - categorization failed", url)
            continue
        website.category = category
        crawl_id = crawl_ids[url]
        data_service.save_site_category(crawl_id, category.name)
        logger.info("Categorized %s as %s", url, category.name)
        categorized_websites.append(website)

    ### Extraction
    for website in categorized_websites:
        url = website.url
        category = website.category
        crawl_id = crawl_ids[url]
        extracted = extraction_service.extract_information(website.html, website.category, website.url)
        if extracted:
            extracted, links = extracted
            if category.is_list_category:
                for entry in extracted:
                    data_service.save_extraction(crawl_id, entry)
                logger.info("Extracted %d entries from %s", len(extracted), url)
            else:
                data_service.save_extraction(crawl_id, extracted)
                logger.info("Extracted %d field(s) from %s", len(extracted), url)
            for link in links:
                fetching_service.queue_url(link)
        else:
            logger.debug("No data extracted from %s (category=%s)", url, category.name)

    monitor_service.round_end()